"""add profiling_tasks table

Revision ID: f0451d4f4254
Revises:
Create Date: 2026-02-20 23:45:25.615804

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0451d4f4254"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiling_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("datasource_type", sa.String(length=50), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=True),
        sa.Column("progress_phase", sa.String(length=50), nullable=True),
        sa.Column("progress_detail", sa.JSON(), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiling_tasks_status"), "profiling_tasks", ["status"], unique=False)
    op.create_index("ix_profiling_tasks_status_created", "profiling_tasks", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profiling_tasks_status_created", table_name="profiling_tasks")
    op.drop_index(op.f("ix_profiling_tasks_status"), table_name="profiling_tasks")
    op.drop_table("profiling_tasks")
    # ### end Alembic commands ###
